docs: update readme
chkware/vscode-ext pull request #24
Opened 2022-08-27 11:32 UTC by 0hsn

2022-08-28 13:13 UTC, arifszn requested changes

2022-08-28 13:13 UTC, arifszn commented on README.md
> +Please use tag `chkware-cli` with the question on [stackoverflow.com](https://stackoverflow.com/questions/tagged/chkware-cli) to ask or discuss anything. Follow the tag if you want to help others wit
Maybe issue tracker link also?
```markdown
### How do I report feedback and issues?

You can [file an issue](https://github.com/chkware/vscode-ext/issues) on the GitHub repo.
```

2022-08-28 13:13 UTC, arifszn commented on README.md
> +Get started writing `chkware` configurations with VS Code in three steps:
```suggestion
Get started writing `chkware` configurations with VS Code in two steps:
```

2022-08-28 13:28 UTC, arifszn commented
![Untitled 2](https://user-images.githubusercontent.com/45073703/187076290-ac2d2fad-5335-4cec-90b2-0e5c500d8ebc.gif)

Can this gif be used?

2022-08-28 13:38 UTC, 0hsn commented
> ![Untitled 2](https://user-images.githubusercontent.com/45073703/187076290-ac2d2fad-5335-4cec-90b2-0e5c500d8ebc.gif)
> 
> Can this gif be used?

Yes, good. but, can you check why syntax coloring is not working? I was supposed to set `YAML` syntax, therefore coloring should be there. or i am getting it wrong.

2022-08-28 13:57 UTC, arifszn commented
> Yes, good. but, can you check why syntax coloring is not working? It was supposed to set `YAML` syntax, therefore coloring should be there. or i am getting it wrong.


As this was already an opened markdown file, the syntax didn't work. But if no opened file were there, it would create a new YAML file. 

![Untitled 5](https://user-images.githubusercontent.com/45073703/187077383-7083de1a-affe-4fed-845a-d71d69d03034.gif)

2022-08-28 14:25 UTC, 0hsn commented
> As this was already an opened markdown file, the syntax didn't work. But if no opened file were there, it would create a new YAML file. Changing an already opened file's formatting language programmatically isn't possible right now.

It's okay of the feature is not available. But, at least the gif looks okay now

2022-08-31 17:09 UTC, arifszn approved these changes

2022-09-01 07:22 UTC, merged